title: Vår Livsstil
short_title: Vår Livsstil
description:
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  posts:
    output: true
    permalink: /blog/:title/

jekyll-archives:
  enabled: all
  layout: "archive"

plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives

sass:
  style: compressed
